/**
 * Phase 25.2 — GraphOverview vitest coverage.
 *
 * Covers: loading / error / populated states, AI summary button toggling,
 * warnings disclosure, refresh button wiring.
 */

import React from 'react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';

import GraphOverview from '../src/components/graph/GraphOverview';
import type {
  GraphSchemaResponse,
  GraphSchemaSummaryResponse,
} from '../src/services/graphApi';

vi.mock('../src/hooks/useGraphSchema', () => ({
  useGraphSchema: vi.fn(),
  useIntrospectGraph: vi.fn(),
  useGraphSchemaSummary: vi.fn(),
}));

import {
  useGraphSchema,
  useGraphSchemaSummary,
  useIntrospectGraph,
} from '../src/hooks/useGraphSchema';

const baseSchema: GraphSchemaResponse = {
  connection_id: 1,
  provider: 'neo4j',
  database_name: 'neo4j',
  labels: [],
  relationships: [],
  patterns: [
    {
      source_labels: ['User'],
      relationship_type: 'PURCHASED',
      target_labels: ['Order'],
      estimated_count: 42,
    },
  ],
  indexes: [],
  constraints: [],
  warnings: ['Counted first 100 labels of 250'],
  collected_at: '2026-05-16T12:00:00+00:00',
  schema_updated_at: '2026-05-16T12:00:00+00:00',
  server_version: '5.18.0',
  edition: 'community',
  label_count: 5,
  relationship_type_count: 2,
  pattern_count: 1,
  index_count: 1,
  constraint_count: 0,
  cached: true,
};

function setup({
  schema = baseSchema,
  loading = false,
  isError = false,
  introspectPending = false,
  summarizeData = undefined as GraphSchemaSummaryResponse | undefined,
  summarizePending = false,
  summarizeError = null as Error | null,
} = {}) {
  const introspectMutate = vi.fn();
  const summarizeMutate = vi.fn();
  (useGraphSchema as any).mockReturnValue({
    data: schema,
    isLoading: loading,
    isError,
    error: isError ? { message: 'boom' } : null,
    refetch: vi.fn(),
  });
  (useIntrospectGraph as any).mockReturnValue({
    mutate: introspectMutate,
    isPending: introspectPending,
  });
  (useGraphSchemaSummary as any).mockReturnValue({
    mutate: summarizeMutate,
    isPending: summarizePending,
    data: summarizeData,
    isError: !!summarizeError,
    error: summarizeError,
  });
  return { introspectMutate, summarizeMutate };
}

describe('GraphOverview', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('shows hint when no connection selected', () => {
    setup();
    render(<GraphOverview connectionId={null} />);
    expect(
      screen.getByText(/Select a Neo4j connection/i),
    ).toBeInTheDocument();
  });

  it('renders loading state', () => {
    setup({ loading: true });
    render(<GraphOverview connectionId={1} />);
    expect(screen.getByText(/Loading graph schema/i)).toBeInTheDocument();
  });

  it('renders error state with retry', () => {
    setup({ isError: true });
    render(<GraphOverview connectionId={1} />);
    expect(screen.getByText(/Failed to load schema/i)).toBeInTheDocument();
    expect(screen.getByRole('button', { name: /Retry/i })).toBeInTheDocument();
  });

  it('renders counts and top patterns', () => {
    setup();
    render(<GraphOverview connectionId={1} connectionName="prod-graph" />);
    expect(screen.getByText('prod-graph')).toBeInTheDocument();
    expect(screen.getByText(/Server 5.18.0/)).toBeInTheDocument();
    // Stat cards
    expect(screen.getByText('Node labels')).toBeInTheDocument();
    expect(screen.getByText('5')).toBeInTheDocument();
    // Pattern rendered
    expect(screen.getByText(/PURCHASED/)).toBeInTheDocument();
  });

  it('Refresh button triggers introspect mutation', () => {
    const { introspectMutate } = setup();
    render(<GraphOverview connectionId={1} />);
    fireEvent.click(screen.getByRole('button', { name: /Refresh schema/i }));
    expect(introspectMutate).toHaveBeenCalledTimes(1);
  });

  it('Generate summary button calls summarize mutation', () => {
    const { summarizeMutate } = setup();
    render(<GraphOverview connectionId={1} />);
    fireEvent.click(
      screen.getByRole('button', { name: /Generate summary/i }),
    );
    expect(summarizeMutate).toHaveBeenCalledTimes(1);
  });

  it('renders summary text when present', () => {
    setup({
      summarizeData: {
        connection_id: 1,
        summary: 'A small social graph of users and orders.',
        model: 'llama3',
        provider: 'ollama',
        used_fallback: false,
      },
    });
    render(<GraphOverview connectionId={1} />);
    expect(
      screen.getByText(/A small social graph/i),
    ).toBeInTheDocument();
    // Provenance line is rendered
    expect(screen.getByText(/Generated by ollama/i)).toBeInTheDocument();
  });

  it('labels fallback summary clearly', () => {
    setup({
      summarizeData: {
        connection_id: 1,
        summary: 'Deterministic blurb.',
        model: null,
        provider: null,
        used_fallback: true,
      },
    });
    render(<GraphOverview connectionId={1} />);
    expect(
      screen.getByText(/Deterministic fallback summary/i),
    ).toBeInTheDocument();
  });

  it('toggles warnings disclosure', () => {
    setup();
    render(<GraphOverview connectionId={1} />);
    // Warnings header shows count but list is collapsed
    expect(screen.getByText(/Introspection warnings/i)).toBeInTheDocument();
    expect(
      screen.queryByText(/Counted first 100 labels/i),
    ).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: /Show/i }));
    expect(
      screen.getByText(/Counted first 100 labels/i),
    ).toBeInTheDocument();
  });
});
